### ISSUE TITLE
Error when installing plugin

### ISSUE THREAD

**Issue by OneX** [putyourlightson/craft-snaptcha#1]
This error I get when trying to update database:

yii\base\ErrorException: preg_split() expects parameter 2 to be string, array given

Migration: putyourlightson\snaptcha\migrations\m181009_120000_update_blacklist_settings

Output:

Exception: preg_split() expects parameter 2 to be string, array given (/Users/josipanic/Sites/four-inc/vendor/putyourlightson/craft-snaptcha/src/migrations/m181009_120000_update_blacklist_settings.php:24)
#0 /Users/josipanic/Sites/four-inc/vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError(2, 'preg_split() ex...', '/Users/josipani...', 24)
#1 [internal function]: craft\web\ErrorHandler->handleError(2, 'preg_split() ex...', '/Users/josipani...', 24, Array)
#2 /Users/josipanic/Sites/four-inc/vendor/putyourlightson/craft-snaptcha/src/migrations/m181009_120000_update_blacklist_settings.php(24): preg_split('/\\r\\n|\\r|\\n/', Array)
#3 /Users/josipanic/Sites/four-inc/vendor/craftcms/cms/src/db/Migration.php(56): putyourlightson\snaptcha\migrations\m181009_120000_update_blacklist_settings->safeUp()
#4 /Users/josipanic/Sites/four-inc/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#5 /Users/josipanic/Sites/four-inc/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(putyourlightson\snaptcha\migrations\m181009_120000_update_blacklist_settings))
#6 /Users/josipanic/Sites/four-inc/vendor/craftcms/cms/src/services/Updates.php(223): craft\db\MigrationManager->up()
#7 /Users/josipanic/Sites/four-inc/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(521): craft\services\Updates->runMigrations(Array)
#8 /Users/josipanic/Sites/four-inc/vendor/craftcms/cms/src/controllers/UpdaterController.php(209): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#9 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#10 /Users/josipanic/Sites/four-inc/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /Users/josipanic/Sites/four-inc/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#12 /Users/josipanic/Sites/four-inc/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('migrate', Array)
#13 /Users/josipanic/Sites/four-inc/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#14 /Users/josipanic/Sites/four-inc/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('updater/migrate', Array)
#15 /Users/josipanic/Sites/four-inc/vendor/craftcms/cms/src/web/Application.php(683): craft\web\Application->runAction('updater/migrate')
#16 /Users/josipanic/Sites/four-inc/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#17 /Users/josipanic/Sites/four-inc/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /Users/josipanic/Sites/four-inc/public/index.php(21): yii\base\Application->run()
#19 {main}

**Comment by putyourlightson** [comment]
Thanks, fixed in version 2.1.1, please update the plugin (using composer if possible) before running the database update.
