### ISSUE TITLE
Unable to exclude controller from Snaptcha's validation

### ISSUE THREAD

**Issue by peteeveleigh** [putyourlightson/craft-snaptcha#10]
I'm trying to prevent Snaptcha from validating the consent form generated by Complete Cookie Consent.
The form posts to complete-cookie-consent/consent/submit so I have added ^complete-cookie-consent/consent/submit$ to the excluded uri patterns in Snaptcha's settings.

However, the form is still being blocked by Snaptcha.

How should I do this, bearing in mind it's not ideal for me to be modifying the controller and disabling Snaptcha that way?

**Comment by bencroker** [comment]
Instead of disabling Snaptcha validation of the submitted form, would it not be easier (and more secure) to add a Snaptcha field to the form using `{{ craft.snaptcha.field }}`?

**Comment by peteeveleigh** [comment]
I'm not sure that's going to be possible without modifying the plugin. I believe it auto-injects the form.
But saying that it might be possible to override the template - I'll take a closer look. 👍

**Comment by bencroker** [comment]
According to the [docs](https://github.com/nilsenpaul/craft-complete-cookie-consent#updating-cookie-consent-preferences-with-your-own-form):

> As of v1.0.1, it's possible to update consent preferences for a visitor with a form like this

**Comment by peteeveleigh** [comment]
I've had a quick look and it seems that those docs are referring to making a form to manage preferences.
The actual cookie banner is injected by the plugin and I can't find any way to override it in order to add the Snaptcha tag.

Is there any way I can disable Snaptcha just for that form/controller until I figure out a better solution?

**Comment by peteeveleigh** [comment]
For the moment I've modified the Cookie Consent Controller to exclude Snaptcha validation with
`    public $enableSnaptchaValidation = false;`

The dev of the plugin is looking at adding a means to add content into the consent banner form too. So I think this can be closed now.

Cheer Ben, thanks for the help. 👍

**Comment by bencroker** [comment]
I was just about to suggest using `$enableSnaptchaValidation`, glad you found it!
