### ISSUE TITLE
Allow validation enabling in specific controllers instead of disabling

### ISSUE THREAD

**Issue by stenvdb** [putyourlightson/craft-snaptcha#11]
Right know you can enable validation on all post requests and then disable when wanted using the `enableSnaptchaValidation` property. I would like a way to turn this around: disable it by default but a way to enable it when wanted.

For example: I have come across multiple situations where the plugin is validating where it doesn't need to be. The last example of this is that this plugin blocks all webhook requests from payment providers. Right now I'm doing things like:

```
Event::on(CartController::class, CartController::EVENT_BEFORE_ACTION, function(ActionEvent $event) {
    $sender = (array)$event->sender;
    $sender['enableSnaptchaValidation'] = false;
    $event->sender = (object)$sender;
});

Event::on(WebhooksController::class, WebhooksController::EVENT_BEFORE_ACTION, function(ActionEvent $event) {
    $sender = (array)$event->sender;
    $sender['enableSnaptchaValidation'] = false;
    $event->sender = (object)$sender;
});

...
```

Usually though I only need this plugin to do it's thing at a guest entries form. It would be a lot easier to just be able to enable it there. Right now I have to disable it manually in a lot of places, it would be easier to turn this around. What do you think?

**Comment by bencroker** [comment]
Your suggestion would mean that anyone installing the plugin would have to write a module/plugin to turn on validation of specific form submissions, which is out of the question. Snaptcha protects all POST requests by default and allows disabling validation through the use of URI patterns to exclude and the `$enableSnaptchaValidation` property.

The way you have handled disabling validation for the cart and webhooks controllers looks perfect.

**Comment by stenvdb** [comment]
> Your suggestion would mean that anyone installing the plugin would have to write a module/plugin to turn on validation of specific form submissions

This is true for simple sites. But currently everyone who uses this plugin together with Craft Commerce has to write a module as well because you need to disable validation in the webhooks controller as a bare minimum. If it can't be implemented in the plugin, perhaps a Craft Commerce section in the documentation would be helpful?

**Comment by bencroker** [comment]
I've added the ability to exclude specific controller actions from validation in https://github.com/putyourlightson/craft-snaptcha/commit/c8e6e570c9f674db978e4202d7962e793e99310e and added `commerce/webhooks/process-webhook` as the default. Can you test if this works for you?

**Comment by bencroker** [comment]
Released in 2.3.0.

**Comment by stenvdb** [comment]
Hi @bencroker ,

Thank you for adding this. Just tested this and works like a charm:
```
Event::on(SnaptchaService::class, SnaptchaService::EVENT_BEFORE_EXCLUDE_CONTROLLER_ACTIONS, function(ValidateFieldEvent $event) {
    $excludeControllerActions = $event->excludeControllerActions;
    array_push($excludeControllerActions, 'commerce/cart/update-cart', 'mailchimp-subscribe/audience/subscribe');
    $excludeControllerActions = array_unique($excludeControllerActions);
    $event->excludeControllerActions = $excludeControllerActions;
});
```
Saves me some duplicate code in my business logic module.

**Comment by bencroker** [comment]
Great!
