### ISSUE TITLE
Snaptcha 2.2.5 is in conflict with / blocks GDPR Cookie Consent 1.4.4 Plugin from storing consents

### ISSUE THREAD

**Issue by axelhebenstreit** [putyourlightson/craft-snaptcha#12]
Craft CMS 3.5.15.1
Snaptcha 2.2.5
GDPR Cookie Consent 1.4.4

Install GDPR Cookie Consent 1.4.4
check if it works properly and is storing consents
Install Snaptcha 2.2.5
GDPR Cookie Consent 1.4.4 stops storing consents because Snaptcha 2.2.5 is blocking GDPR Cookie Consent 1.4.4

`error: yii\web\HttpException:403` @ https://damin.tld/index.php?p=actions/ 

`yii\web\ForbiddenHttpException: Sorry, you have not passed the security test. Please make sure that you have Javascript enabled and that you update the page you are trying to submit. in /srv/users/axel/apps/craft/vendor/putyourlightson/craft-snaptcha/src/Snaptcha.php:123
Stack trace:
#0 /srv/users/axel/apps/craft/vendor/putyourlightson/craft-snaptcha/src/Snaptcha.php(73): putyourlightson\snaptcha\Snaptcha->validateField(Object(yii\base\ActionEvent))
#1 [internal function]: putyourlightson\snaptcha\Snaptcha->putyourlightson\snaptcha\{closure}(Object(yii\base\ActionEvent))
#2 /srv/users/axel/apps/craft/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(yii\base\ActionEvent))
#3 /srv/users/axel/apps/craft/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\web\\Contr...', 'beforeAction', Object(yii\base\ActionEvent))
#4 /srv/users/axel/apps/craft/vendor/yiisoft/yii2/base/Controller.php(299): yii\base\Component->trigger('beforeAction', Object(yii\base\ActionEvent))
#5 /srv/users/axel/apps/craft/vendor/yiisoft/yii2/web/Controller.php(200): yii\base\Controller->beforeAction(Object(yii\base\InlineAction))
#6 /srv/users/axel/apps/craft/vendor/craftcms/cms/src/web/Controller.php(138): yii\web\Controller->beforeAction(Object(yii\base\InlineAction))
#7 /srv/users/axel/apps/craft/vendor/yiisoft/yii2/base/Controller.php(178): craft\web\Controller->beforeAction(Object(yii\base\InlineAction))
#8 /srv/users/axel/apps/craft/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('update', Array)
#9 /srv/users/axel/apps/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('update', Array)
#10 /srv/users/axel/apps/craft/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('cookie-consent/...', Array)
#11 /srv/users/axel/apps/craft/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction('cookie-consent/...', Array)
#12 /srv/users/axel/apps/craft/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#13 /srv/users/axel/apps/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#14 /srv/users/axel/apps/craft/public/index.php(22): yii\base\Application->run()
#15 {main}`

**Comment by bencroker** [comment]
Added a validation exception for this plugin in https://github.com/putyourlightson/craft-snaptcha/commit/fa301308b1e98b88aad34776e2ca4f62930a9dc1 for the next release.

**Comment by bencroker** [comment]
Released in 2.3.0.

**Comment by nordentwickler** [comment]
Hey @bencroker could you exclude https://plugins.craftcms.com/complete-cookie-consent as well? 

https://github.com/nilsenpaul/craft-complete-cookie-consent/issues/24

Greetings, Marten

**Comment by bencroker** [comment]
@nordentwickler Added in https://github.com/putyourlightson/craft-snaptcha/commit/05523c9c9cea510eadb32f61481a66f316ecdd2e and released in 2.3.1.
