### ISSUE TITLE
Compatibility with verbb / comments

### ISSUE THREAD

**Issue by luke-nehemedia** [putyourlightson/craft-snaptcha#13]
I recently found your plugin since I searched for a good solution for form validation that was compatible with Blitz. 

So far I managed to get all other form plugins (Freeform, Wheelform etc.) to work with this plugin. However, the only one that does not work so far is verbb/comments. 

Is there any information on this?
I tried to include the code via blitz inject, but I always get this error message:

> Value not found in database. [https://www.website.com/index.php?p=actions/comments/comments/save]

Would really appreciate any help or information.

**Comment by bencroker** [comment]
> I tried to include the code via blitz inject, but I always get this error message:

Can you paste your injected Blitz code here? Also version numbers for the Snaptcha, Blitz and Comments plugin would be useful to know.

**Comment by luke-nehemedia** [comment]
Sorry it took me so long to reply. I was not able to work on this earlier because of some corona issues. 

I have managed to get comments to work with two problems still persisting:
1) "additional spam protection" must be disabled in the settings. I have contacted verbb about this and I will post the solution here if I find one. 
2) sometimes the javascript Ajax-submit method does not work for whatever reason and the form is sent via post and the page reloaded. In this case, no success/failure message is displayed. I also asked verbb for a solution and will update this post accordingly. 

Otherwise it works fine.

This is the way I did it:

**Step 1:** In my **template** I included comments via this way:
```
{{ craft.comments.renderCss(commentsId) }}
{{ craft.blitz.getUri('/comments/'~commentId) }}
{{craft.comments.renderJs(commentId)}}
```

I will probably add the CSS into my main template in the future and would also suggest you do so. Unfortunately you cannot use `craft.comments.renderCss` without an `elementId` - I do not know why since the css is unrelated to the element-id, in contrast to the javascript. 

**Step 2:** I created a **route** to a separate template 
This template will be injected by Blitz via `comments/id` as you can see above in step 1. 
Note that you have to include the JS in your main template since it will not be executed if injected. Once again, you can "clean" it up even more if you include the js file at the end before `</body>` and built the `<script>` tag that initiates form yourself. 

```
{% set commentsId = craft.app.request.segment(2) %}
{{ craft.comments.render(commentsId) }}
```

**Step 3:** Modify **custom comments template**
You have  to duplicate the default templates and include the snapcha code. Once again, the default `craft.snaptcha.field` won't work since it relies on javascript to be executed which will not work in the injected code. Therefore you have to do it manually:

form.html (but the same applies to other template files)
```
<form class="cc-f-wrap" role="form" method="post" accept-charset="UTF-8" {% if containsFileInput %}enctype="multipart/form-data"{% endif %}>
            <input type="hidden" name="action" value="comments/comments/save">
            <input type="hidden" name="elementId" value="{{ element.id }}">

            ............... // .................

            {# Include snaptcha Code with the normal csrf #}
            <input type="hidden" id="my-snaptcha-field"
                      name="{{ craft.snaptcha.fieldName }}" 
                      value="{{ craft.snaptcha.fieldValue }}">
            {{ csrfInput() }}

            ............... // .................

            {{ craft.comments.protect() }}

```

The same changes have to be applied for all the small forms for voting etc. These will probably work only once, since the page is not reloaded, but that should not cause problems since you can only vote once either way ;)

I hope this helps. I will update this post when I have heard from verbb or found another solution (or more problems 😀)

**Comment by bencroker** [comment]
Thanks for posting your solution. FYI you can also include the Snaptcha field as follows, assuming you don't require the `id` attribute:

```twig
{{ craft.snaptcha.field }}
```

**Comment by luke-nehemedia** [comment]
I tried this (as described above) but this did not work, since no javascript in the injected code will be executed. 
The code from `{{ craft.snaptcha.field }}` worked by setting the value of the field via javascript, therefore this did not work.

**Comment by bencroker** [comment]
Ah yes, of course, my mistake.
