### ISSUE TITLE
Unknown Property Error

### ISSUE THREAD

**Issue by CreateSean** [putyourlightson/craft-snaptcha#14]
### Describe the bug
I updated a site from Craft 2 to Craft 3.6.11.1

And now when visiting a page with `{{ craft.snaptcha.field }}` I get this error:

```
Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: putyourlightson\snaptcha\records\SnaptchaRecord::expirationTime
1. in /var/www/html/vendor/yiisoft/yii2/base/Component.phpat line 210
```
If I comment out `{{ craft.snaptcha.field }}` the page loads correctly

Snaptcha Validation Enabled is turned on.

### To reproduce
Steps to reproduce the behaviour:
1. add `{{ craft.snaptcha.field }}` to a form template
2. visit page, get error

### Expected behaviour
I would expect my page to load and display the form.

### Versions
- Plugin version:2.3.1
- Craft version:3.6.11.1

**Comment by bencroker** [comment]
It sounds like one of the migrations was not run successfully. Try uninstalling and installing the plugin from the control panel (or with the console command) and that should resolve it.

**Comment by CreateSean** [comment]
Confirmed working now. Thank you.
