### ISSUE TITLE
Snaptcha spam captured but still posting the form

### ISSUE THREAD

**Issue by philipboomy** [putyourlightson/craft-snaptcha#16]
### Describe the bug
When posting a Craft Campaign form (subscribe) I can force the error "For some reason your submission was flagged as spam. Please click the button below to resubmit your data."  by not using the Snaptcha Twig tag but the submission is actually successful as subscriber gets double opt in email.

### To reproduce
Steps to reproduce the behaviour:
1. Add a Craft Campaign form without Snaptcha Twig tag
2. Post it
3. See error message
4. Check that subscriber is actually subscribed (or at least is send the double opt in email)

### Expected behaviour
Stop the form submission

### Screenshots
https://share.getcloudapp.com/p9ubLP1p
https://share.getcloudapp.com/2Nuw6549

### Versions
- Plugin versions:
- Campaign 1.19.1
- Snaptcha 3.0.2
- Craft version: 3.6.12

**Comment by bencroker** [comment]
Thanks for reporting, fixed in version 3.0.3.
