### ISSUE TITLE
Disabling validation on controller class no longer working in 3.7.4

### ISSUE THREAD

**Issue by codyjames** [putyourlightson/craft-snaptcha#18]
### Describe the bug
Disabling validation on a controller class no longer working in 3.7.4

### To reproduce
Steps to reproduce the behaviour:
1. Migrate to 3.7.4
2. Test a controller action that should have snaptcha disabled

### Expected behaviour
Snaptcha shouldn't try to run on that form

### Versions
- Plugin version: 3.0.7
- Craft version: 3.7.4

**Comment by bencroker** [comment]
> Test a controller action that should have snaptcha disabled

Which controller action are you testing and how specifically is Snaptcha disabled?

**Comment by codyjames** [comment]
@bencroker It's a controller action for a custom module. It's disabled through `public $enableSnaptchaValidation = false;` on the controller.

**Comment by bencroker** [comment]
I just tested locally and it appears to still be working fine. What is the exact outcome of your test?

Here is an example of `$enableSnaptchaValidation` being used: 
https://github.com/putyourlightson/craft-blitz/blob/fac649e3857dcf74a73f803a148071fb643f78a2/src/controllers/CacheController.php#L29
