### ISSUE TITLE
JavaScript must be enabled for your submission to be verified. Please enable it and refresh the page.

### ISSUE THREAD

**Issue by philipboomy** [putyourlightson/craft-snaptcha#19]
### Describe the bug
I am getting this error "JavaScript must be enabled for your submission to be verified. Please enable it and refresh the page." when submitting via Ajax to the guest entry plugin. Might happen when doing normal post requests too. I have added this "guest-entries/save" to the section "Exclude Controller Actions" and it used to work fine so assume its some of the last updates causing issue.

Not sure if these are related #18 and #15 

### Versions
- Plugin version: 3.0.7
- Craft version: 3.7.7

**Comment by bencroker** [comment]
You need to specify the controller action whereas you have only specified the controller – `guest-entries/save/index` should work.

**Comment by philipboomy** [comment]
Thanks. That was it. Used to work though but still a user error, so apologies for false alarm.

**Comment by bencroker** [comment]
It may have worked with the “Excluded URI Patterns” setting which was removed in [version 3.0.0](https://github.com/putyourlightson/craft-snaptcha/blob/develop/CHANGELOG.md#300---2021-04-13). The new “Exclude Controller Actions” setting works differently and requires the full controller action path.
