### ISSUE TITLE
Craft v2 version?

### ISSUE THREAD

**Issue by billymedia** [putyourlightson/craft-snaptcha#2]
You mention that there is a version for craft 2, is it possible to get a copy? i need to add captcha support to formerly.

**Comment by putyourlightson** [comment]
Sure, please purchase a license through the Craft 3 Plugin Store (https://plugins.craftcms.com/snaptcha) and send your receipt to info@putyourlightson.net. We will then email you the legacy version of the plugin for Craft 2.

**Comment by billymedia** [comment]
Ah ok , thanks!
