### ISSUE TITLE
Excluded forms showing up in Snaptcha logs

### ISSUE THREAD

**Issue by AdamChlan** [putyourlightson/craft-snaptcha#20]
I have excluded the login (users/login) and password reset form (users/send-password-reset-email) from Snaptcha, but I am seeing the pages which those forms live on be logged in the Snaptcha logs. Is this something I should expect? Things test well for me on the front end, but I'm worried other users are having issues.

**Comment by bencroker** [comment]
How exactly have you excluded them and what are you seeing in the logs?

**Comment by AdamChlan** [comment]
In the Exclude Controller Actions table in the plugin settings in the control panel I added the following:

users/login
users/send-password-reset-email

In the logs I am seeing:

2021-08-24 12:45:21 [][][info] Value submitted is null. [https://URL-HERE/login]
2021-08-24 12:33:29 [][][info] Value submitted is null. [https://URL-HERE/account/password-reset]

**Comment by bencroker** [comment]
The best way to ensure it is working is to view the source code of the page. If your forms do _not_ contain a hidden input field with name `snaptcha` but still successfully submit then all is well.

Do you perhaps have other forms on the `/login` and `/account/password-reset` forms that are not excluded from validation?

**Comment by AdamChlan** [comment]
The hidden input is not on these forms, and I personally have no problem using them. There are no other forms on these pages. My main concern are the logs showing these pages, and I did get a report of someone having an issue with a form, which I am trying to clarify which one was causing an issue. I'll report back if any additional findings come in. Thanks for the info.

**Comment by AdamChlan** [comment]
So it turns out I was able to reproduce the issue on the login form by submitting the form with the wrong password. I get the Snaptcha validation error message when doing this. Seems like it should be out of the equation if I have excluded it, correct?

**Comment by AdamChlan** [comment]
After some digging we could see another action was being run when Craft validation was triggered due to an incorrect password - `templates/render`. We added that to our exclude list and it seemed to solve the issue. We now no longer get the Snaptcha notification when entering a the wrong password. Any red flags you can see with this fix?

**Comment by bencroker** [comment]
Thanks for tracking this down!! Fixed in https://github.com/putyourlightson/craft-snaptcha/commit/c129cdf4821d2121def7c44b9d90bb0ddde96207 and released in version 3.0.8.
