### ISSUE TITLE
Extended logging

### ISSUE THREAD

**Issue by peteeveleigh** [putyourlightson/craft-snaptcha#22]
Is there any scope to increase the detail in the logging?

It could be useful to at least log the IP of any trapped form submissions.

If there was also an option to log the actual submitted data, and the time it took to complete the form that would also be quite handy for ensuring we aren't blocking legitimate submissions.

Maybe an "enhanced logging" mode with some kind of pruning to prevent generating enormous log files?

**Comment by bencroker** [comment]
You can log IP addresses by setting the [storeUserIps](https://docs.craftcms.com/api/v3/craft-config-generalconfig.html#storeuserips) general config setting set to `true`.

Logging the submitted data might sound tempting, but it also allows spammers to start spamming your log files, which we're trying to avoid. We could log only the first X characters, but then there is a chance of losing valuable data. Similarly, pruning log files could also lead to loss of important data.

**Comment by peteeveleigh** [comment]
Aha! Thanks for the tip about the IPs.

Hear what you're saying about logging details too.
