### ISSUE TITLE
Craft Commerce Site and Excluding for all forms except registration

### ISSUE THREAD

**Issue by terryupton** [putyourlightson/craft-snaptcha#26]
Hi @bencroker 

I am looking to use Snaptcha on a craft commerce site but purely for the craft (user) registration form only.
My understanding from reading the docs and discussions on Discord is that in order to do this I would need to implement a list of all the 'Exclude Controller Actions' as well as this I would need to manually add some code to my custom controllers (I have a few for subscriptions).

The site in question, as with most commerce sites, has many forms that are on the whole not a problem in regards to spam, mostly due to the fact some are behind the account functionality and others are only successfully along with payment details. thus I feel adding Snaptcha to all forms, seems overkill and adds much more work.

My concern, however, is the exclusion list and that this felt risky incase I missed off some by accident, and adding to custom controllers would also require additional testing when in fact these are not necessary.

Is there another method I am overlooking where it can only be implemented to a specific form(s) or is the above, in fact the only approach possible. Adding to this, if I was to disable the `Validate Users` setting, would this in fact negate a host of these as many of these forms are behind a user account (address management, card management, subscriptions etc). it would still need some exclusions for guest and standard checkouts/adding to carts etc.

A nice feature potentially, would be the ability to 'exclude commerce' where a toggle would bypass all the standard commerce controllers. This is only a thought.

Would love to hear your thoughts on this and the best approach for my situation, whereby I am hoping to eliminate registration spam quickly and easily with little much friction in the first instance. 

Thanks
Terry

**Comment by bencroker** [comment]
As per the [docs](https://putyourlightson.com/plugins/snaptcha#disabling-validation), the [`EVENT_BEFORE_VALIDATE_FIELD`](https://github.com/putyourlightson/craft-snaptcha/blob/ac93605be59d41aa74bb84cb4fbdbda85093b30d/src/services/SnaptchaService.php#L165-L171) event can be used via a custom module/plugin to skip validation for all controller actions except for `users/save-user`, which is what user registration forms (and user edit forms) use.

```php
use putyourlightson\snaptcha\events\ValidateFieldEvent;
use putyourlightson\snaptcha\services\SnaptchaService;
use yii\base\Event;

Event::on(SnaptchaService::class, SnaptchaService::EVENT_BEFORE_VALIDATE_FIELD,
    function (ValidateFieldEvent $event) {
        $action = $event->action ? $event->action->getUniqueId() : null;

        // Skips validation for all controller actions except for `users/save-user`
        if ($action !== 'users/save-user') {
            $event->skipValidation = true;
        }
    }
);
```
