### ISSUE TITLE
Sprig, Snaptcha and Form

### ISSUE THREAD

**Issue by pimago** [putyourlightson/craft-snaptcha#28]
Hi Ben, 
I still think it's more related to Snaptcha than to Sprig. But it's hard to find out since no error is logged in Craft.
There is a 400 error in the browser console.

```
[Error] Failed to load resource: the server responded with a status of 400 () (index.php, line 0)
[Error] Response Status Error Code 400 from https://lappat23.ddev.site/index.php?p=actions/sprig-core/components/render&sprig:action=79de09316f36e9be9c0e39b636d039cf5f4b6f140de4f301abb766a460a80854contact-form/send
```

When I turn off Snaptcha. The form loaded with Sprig is working fine.
When I load the form without Sprig and leave Snaptcha on it is working, but the browser console still shows a 400 error.

`[Error] Failed to load resource: the server responded with a status of 400 () (contact, line 0)`

I thought it might be related to my custom fields or validation. But when I turn these is off there is still a 400 error.
I get the same error with an entry form. Also no 400 error is in the Craft log files.

All plugins and Craft are up to date.

**Comment by bencroker** [comment]
Can you provide some code for the simplest possible template in which this happens, so I can replicate locally? Also, have you checked the request response in the network tab of the browser dev tools with `devMode` enabled?

**Comment by pimago** [comment]
This is a simplified test template which also gives me the error

```twig
{% if errors is defined %}
	<p class="message error">error message</p>
	{% macro errorList(errors) %}
		{% if errors %}
			class="error"
		{% endif %}
	{% endmacro %}
{% endif %}

{% set submission = submission ?? null %}
<form  method="post" action="" accept-charset="UTF-8">
	{{ csrfInput() }}
	{{ actionInput('contact-form/send') }}
	{{ redirectInput('contact') }}
	{{ craft.snaptcha.field }}

	<label for="from-name" {{ submission ? _self.errorList(submission.getErrors('fromName')) }}>Name<span class="txtRed">*</span></label>
	{{ input('text', 'fromName', submission.fromName ?? '', {
		id: 'from-name',
		autocomplete: 'name',
	}) }}

	<label for="from-email" {{ submission ? _self.errorList(submission.getErrors('fromEmail')) }}>E-Mail<span class="txtRed">*</span></label>
	{{ input('email', 'fromEmail', submission.fromEmail ?? '', {
		id: 'from-email',
		autocomplete: 'email',
	}) }}

	{{ hiddenInput('subject','test') }}

	<label for="message" {{ submission ? _self.errorList(submission.getErrors('message.body')) }}>{{'Message'|t}}<span class="txtRed">*</span></label>
	{{ tag('textarea', {
		text: submission.message.body ?? '',
		id: 'message',
		name: 'message[body]',
		rows: 6,
		cols: 40,
	}) }}

	<button class="btn" type="submit">Submit</button>
</form>
```

This will forward me to the snaptcha confirmation page with this error
`[[Error] Failed to load resource: the server responded with a status of 400 () (test, line 0)`

In the network tab summary is marked red
```
Summary
URL: https://lappat23.ddev.site/test
Status: 400
Source: Network
Address: 127.0.0.1:443

Request
:method: POST
:scheme: https
:authority: lappat23.ddev.site
:path: /test

Response
:status: 400
```

**Comment by bencroker** [comment]
I tested your sample code locally and it works as expected, no errors. You’ll need to enable `devMode` and track down the stack trace in the error logs, to be able to troubleshoot this further.

**Comment by pimago** [comment]
devMode is enabled. Maybe something is preventing the logs to work properly?

**Comment by pimago** [comment]
I just noticed my cart is also not working (sprig). I cannot delete or update items in the cart. Same 400 and nothing is logged.

```
[Error] Failed to load resource: the server responded with a status of 400 () (index.php, line 0)
[Error] Response Status Error Code 400 from https://lappat23.ddev.site/index.php?p=actions/sprig-core/components/render&sprig:action=8257f3cd6b4582a5df2b0b3dbd034048470b89fba95458ed9daad96cfa129e17commerce/cart/update-cart
	x (htmx.min.js:1:26028)
	ce (htmx.min.js:1:26197)
	fe (htmx.min.js:1:25848)
	Ar (htmx.min.js:1:44993)
	(anonymous function) (htmx.min.js:1:40079)
```

**Comment by bencroker** [comment]
Have you checked the response body in the network tab? That is where I’d expect the stack trace to appear. Can you show me a screen shot of it?

**Comment by pimago** [comment]
There is also a 400 status

![Screenshot 2024-03-05 at 20 56 15](https://github.com/putyourlightson/craft-snaptcha/assets/1803987/063cba8b-7ebd-4e9f-9c15-6220ac188f32)

**Comment by bencroker** [comment]
It’s the response **body** that should contain the stack trace.

![CleanShot 2024-03-05 at 18 17 42@2x](https://github.com/putyourlightson/craft-snaptcha/assets/57572400/c961621f-4c47-4ed5-87ac-4af3b299c0d0)

**Comment by pimago** [comment]
OK

Response looks the same with or without sprig.

![Screenshot 2024-03-06 at 06 48 45](https://github.com/putyourlightson/craft-snaptcha/assets/1803987/c1f3d5e1-142a-4c54-9a2a-e3c660138be4)

![Screenshot 2024-03-06 at 06 53 24](https://github.com/putyourlightson/craft-snaptcha/assets/1803987/48ab4b0f-ba41-44d6-a12e-1f8fe0ddd52c)

I tried deleting the cpresources folder. But It didn't help.

**Comment by bencroker** [comment]
Ok, so that is the expected response when Snaptcha determines that a valid `snaptcha` value (from an input field, generally) was not submitted. Your sample code above contains `{{ craft.snaptcha.field }}` which outputs the input field, so I’d expect it to work. Are you caching this code, by any chance? Can you try clearing all caches and retesting? If that still doesn’t help then take a look at the `snaptcha` database table and see if you can find a row with the same `value`.

**Comment by pimago** [comment]
Sorry I think I didn't properly explain my issue. In my example above I was intentionally failing the submission. When I load my form with Sprig and test it by removing the Snaptcha field or pressing submit too fast I am not forwarded to the Snaptcha confirmation page. Instead I get the 400 error.
When I load the form without Sprig and fail it, I am forwarded to the Snaptcha conformation page and everything is working fine, but the browser console shows the 400 error.

I cleared the caches. And checked the database. There is currently only one row in the Snaptcha table.

**Comment by bencroker** [comment]
Oh wow, well that took a while to clarify!

> When I load my form with Sprig and test it by removing the Snaptcha field or pressing submit too fast I am not forwarded to the Snaptcha confirmation page. Instead I get the 400 error.

So this is the real issue, correct? There’s no way to proceed to the confirmation page.

> When I load the form without Sprig and fail it, I am forwarded to the Snaptcha confirmation page and everything is working fine, but the browser console shows the 400 error.

A `400` error is expected, since the original `POST` submission failed, therefore a `bad request` response is sent, containing the confirmation page. 

Assuming I’ve finally understood the issue, Sprig is receiving the `400` error response and not doing anything with it, also expected behaviour. It’s up to you how you want to handle this. One option is to place the following code in the template that calls the `sprig()` function.

```twig
{% js %}
    htmx.on('htmx:responseError', function(event) {
        htmx.trigger(event.detail.target, 'refresh');
    });
{% endjs %}
```

For reference: https://htmx.org/events/#htmx:responseError

This will handle error responses by refreshing the component, which will generate a new CSRF token.You could also add a user-facing message that explains what just happened.

```twig
{% js %}
    htmx.on('htmx:responseError', function(event) {
        htmx.trigger(event.detail.target, 'refresh');

        // The `#error` element should exist outside of the component.
        htmx.find('#error').innerHTML = 'For some reason your submission was flagged as spam. Please submit the form again to resubmit your data.';

        // Alternatively use an alert.
        alert('For some reason your submission was flagged as spam. Please submit the form again to resubmit your data.');
    });
{% endjs %}
```

Does that help?

**Comment by pimago** [comment]
Oh man, thank you. Yes, that solved it!

**Comment by bencroker** [comment]
Glad to hear it! I realise the integration between plugins could be smoother, but it’s difficult to automate, so for now I hope this explains what is happening in enough detail that you can customise it to your heart’s content.
