### ISSUE TITLE
All logs have "Value not found in database"

### ISSUE THREAD

**Issue by andreapasotti** [putyourlightson/craft-snaptcha#29]
### Support Request

Hello!

All my Snaptcha logs have the error "Value not found in database", for various actions.
I'm trying to debug some users that cant' finalize payments, but all I have are these logs with the same description.

Snaptcha 4.0.2
Craft 4.8.9
Commerce 4.5.3

The code is injected in pages that are not cached (I've the latest Blitz plugin installed, and the checkouts uri are not included) via:
`{{ craft.snaptcha.getField({minimumSubmitTime: 0.3}) }}`

I see that the hidden input is correctly entered.

Example of latest log:
`[2024-04-12 07:53:18] Value not found in database. [https://example.com/another-page] [express-forms/submit/index]`
`[2024-04-12 14:34:24] Value not found in database. [https://example.com/] [express-forms/submit/index]`
`[2024-04-12 15:12:58] Value not found in database. [https://example.com/shop/checkout/payment] [commerce/payments/pay]`
`[2024-04-12 15:40:45] Value not found in database. [https://example.com/a-page] [express-forms/submit/index]`
`[2024-04-12 16:58:27] Value not found in database. [https://example.com/shop/checkout] [users/login]`

Hope you can help me.

### Plugin Version

4.0.2

**Comment by bencroker** [comment]
There are instructions on using Sprig with Blitz at https://putyourlightson.com/plugins/snaptcha#ajax-requests

Alternatively, using the following tags, that do not depend on JavaScript, should work when using a dynamic include in Blitz.

```twig
{{ input('hidden', craft.snaptcha.fieldName, craft.snaptcha.fieldValue) }}
```
