### ISSUE TITLE
Breaks password reset

### ISSUE THREAD

**Issue by lenvanessen** [putyourlightson/craft-snaptcha#3]
Hi,

The plugin brakes password reset, since this is a craft default template i can't add the twig tag.
Can fix with adding the url to the exclude list, but would be nicer if it worked out of the box

**Comment by putyourlightson** [comment]
The form should not be validated on the password reset form of the control panel. Is that what you are seeing? 

Can you please show me what you mean by "breaking plugin reset" with a screenshot or error message?

**Comment by lenvanessen** [comment]
Nevermind, got this bug from the client but turned out to be something else
