### ISSUE TITLE
Some spam is still coming through

### ISSUE THREAD

**Issue by rostockahoi** [putyourlightson/craft-snaptcha#4]
Hi, I installed Snaptcha on this site: fotoatelier-meier [dot] de

# Situation
It is working because I already have 206 rejected entries since 2019-09-23 in the log. However 9 spam mails still reached the inbox in this time.
There is only one form on the site, but it is on most pages.
The log: [Snaptcha.log](https://github.com/putyourlightson/craft-snaptcha/files/3697725/Snaptcha.log)

The spam mails defintely come through the contact form because they are saved to the database by Rias' Form plugin.

# Expected
No spam at all is reaching the inbox. Is that even promised by Snaptcha?

# Question
Can I do anything with Snaptcha to prevent even the small remaining amount of spam coming through or do I have to find another solution for that?

**Comment by putyourlightson** [comment]
Sounds like Snaptcha is working as it should be. No spam protection is fool-proof and Snaptcha can only stop spam bots, not human spammers, so it will never be able to reach a 100% rate. 

If you suspect that those 9 spam mails that got through were spam bots then you could try increasing the [min­im­um submit time](https://putyourlightson.com/plugins/snaptcha#minimum-submit-time) to harden the form. You could also try changing the [field name](https://putyourlightson.com/plugins/snaptcha#field-name) to something more random.

**Comment by j-greig** [comment]
Please could you explain what 'min­im­um submit time' means? Having a similar problem with 20-30 spam submissions coming from what appears to be a Chinese bot.

**Comment by bencroker** [comment]
> The minimum time for form submission in seconds (increase this to harden spam blocking).

Any form submitted within X seconds of the form being loaded will be blocked. Make sense?
