### ISSUE TITLE
Yii Error for expiration time after upgrading from v 1.3.1

### ISSUE THREAD

**Issue by carolinecblaker** [putyourlightson/craft-snaptcha#5]
### Describe the bug
A YII Error that yields a stack trace: 
yii\base\UnknownPropertyException: Setting unknown property: putyourlightson\snaptcha\records\SnaptchaRecord::expirationTime in /home/vagrant/Code/petroglyph/deploy/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /home/vagrant/Code/petroglyph/deploy/vendor/yiisoft/yii2/db/BaseActiveRecord.php(324): yii\base\Component->__set('expirationTime', '0')
#1 /home/vagrant/Code/petroglyph/deploy/vendor/yiisoft/yii2/BaseYii.php(558): yii\db\BaseActiveRecord->__set('expirationTime', '0')
#2 /home/vagrant/Code/petroglyph/deploy/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(putyourlightson\snaptcha\records\SnaptchaRecord), Object(putyourlightson\snaptcha\models\SnaptchaModel))
#3 /home/vagrant/Code/petroglyph/deploy/vendor/putyourlightson/craft-snaptcha/src/services/SnaptchaService.php(77): yii\base\BaseObject->__construct(Object(putyourlightson\snaptcha\models\SnaptchaModel))
#4 /home/vagrant/Code/petroglyph/deploy/vendor/putyourlightson/craft-snaptcha/src/variables/SnaptchaVariable.php(41): putyourlightson\snaptcha\services\SnaptchaService->getFieldValue(Object(putyourlightson\snaptcha\models\SnaptchaModel))
#5 /home/vagrant/Code/petroglyph/deploy/vendor/putyourlightson/craft-snaptcha/src/variables/SnaptchaVariable.php(55): putyourlightson\snaptcha\variables\SnaptchaVariable->getFieldValue(NULL)
#6 /home/vagrant/Code/petroglyph/deploy/vendor/twig/twig/src/Extension/CoreExtension.php(1495): putyourlightson\snaptcha\variables\SnaptchaVariable->getField()
#7 /home/vagrant/Code/petroglyph/deploy/vendor/craftcms/cms/src/helpers/Template.php(105): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(putyourlightson\snaptcha\variables\SnaptchaVariable), 'field', Array, 'any', false, false)
#8 /home/vagrant/Code/petroglyph/deploy/storage/runtime/compiled_templates/34/3419e4aa450f249dc017c35b57ab0689a372a9cf076a4018d37937ab2c3cb6da.php(200): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(putyourlightson\snaptcha\variables\SnaptchaVariable), 'field', Array)
#9 /home/vagrant/Code/petroglyph/deploy/vendor/twig/twig/src/Template.php(184): __TwigTemplate_b5d88922a6fbc1f1142c251a438aca31f912514cc946505e8fd001e1fdd272ff->block_content(Array, Array)
#10 /home/vagrant/Code/petroglyph/deploy/storage/runtime/compiled_templates/bc/bcb2c0eb624214da3645593970e8bad20f9028d79c10cdc80ed772bb2f077fd9.php(523): Twig\Template->displayBlock('content', Array, Array)
#11 /home/vagrant/Code/petroglyph/deploy/vendor/twig/twig/src/Template.php(407): __TwigTemplate_3f6d3a1fcdef7c4b1d4dd9104b8cfeaf04c0d61630ff0b8c5c80d4a0f6684c7a->doDisplay(Array, Array)
#12 /home/vagrant/Code/petroglyph/deploy/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#13 /home/vagrant/Code/petroglyph/deploy/storage/runtime/compiled_templates/34/3419e4aa450f249dc017c35b57ab0689a372a9cf076a4018d37937ab2c3cb6da.php(45): Twig\Template->display(Array, Array)
#14 /home/vagrant/Code/petroglyph/deploy/vendor/twig/twig/src/Template.php(407): __TwigTemplate_b5d88922a6fbc1f1142c251a438aca31f912514cc946505e8fd001e1fdd272ff->doDisplay(Array, Array)
#15 /home/vagrant/Code/petroglyph/deploy/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#16 /home/vagrant/Code/petroglyph/deploy/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#17 /home/vagrant/Code/petroglyph/deploy/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#18 /home/vagrant/Code/petroglyph/deploy/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#19 /home/vagrant/Code/petroglyph/deploy/vendor/craftcms/cms/src/web/View.php(344): Twig\Environment->render('index', Array)
#20 /home/vagrant/Code/petroglyph/deploy/vendor/craftcms/cms/src/web/View.php(393): craft\web\View->renderTemplate('index', Array)
#21 /home/vagrant/Code/petroglyph/deploy/vendor/craftcms/cms/src/web/Controller.php(243): craft\web\View->renderPageTemplate('index', Array)
#22 /home/vagrant/Code/petroglyph/deploy/vendor/craftcms/cms/src/controllers/TemplatesController.php(101): craft\web\Controller->renderTemplate('index', Array)
#23 [internal function]: craft\controllers\TemplatesController->actionRender('index', Array)
#24 /home/vagrant/Code/petroglyph/deploy/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#25 /home/vagrant/Code/petroglyph/deploy/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#26 /home/vagrant/Code/petroglyph/deploy/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('render', Array)
#27 /home/vagrant/Code/petroglyph/deploy/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#28 /home/vagrant/Code/petroglyph/deploy/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('templates/rende...', Array)
#29 /home/vagrant/Code/petroglyph/deploy/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#30 /home/vagrant/Code/petroglyph/deploy/vendor/craftcms/cms/src/web/Application.php(284): yii\web\Application->handleRequest(Object(craft\web\Request))
#31 /home/vagrant/Code/petroglyph/deploy/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#32 /home/vagrant/Code/petroglyph/deploy/docs/index.php(21): yii\base\Application->run()
#33 {main}

### To reproduce
Steps to reproduce the behaviour:
1. Update Craft CMS from v 2.6.3 to 3.4.0.b-3
2. Install today's Snaptcha version on site 2.21
3. Add {{craft.snaptcha.field}} to a template

Notably,  {{ craft.snaptcha.fieldName }} does not throw the error. {{ craft.snaptcha.fieldValue }} throws it.

### Expected behaviour
Rendered template with Snaptcha invisibly embedded in the form somewhere.

### Versions
- Plugin version: 2.2.1
- Craft version: 3.4.0.b3

**Comment by carolinecblaker** [comment]
Mitigation: Tried disabling/reenabling Snaptcha. Tried saving new values in field for Expiration Time. I noticed it was first a numeric value but it is now a string - no diff, same result.

**Comment by bencroker** [comment]
It sounds like one of the database migrations was not completed successfully. I see you’re on a beta version of Craft, though that shouldn’t affect the running of migrations. 

For a quick fix, uninstall the plugin from the control panel and install again. That should recreate the database tables and avoid any further errors.

**Comment by carolinecblaker** [comment]
I did this and as expected, no more errors.

However,  

`<input type="hidden" id="foo" v-model='foo' name="{{ craft.snaptcha.fieldName }}" value="{{ craft.snaptcha.fieldValue }}">`

.. still only outputs:

`<input type="hidden" id="foo" name="the_name" value="">`

Note lack of expected value.

Alternately, the use of {{craft.snaptcha.getfield}} would work here for me if it didn't insert JS, which is incompatible with my Vue app.

**Comment by bencroker** [comment]
Glad to hear it! 

> However...

This is a completely new issue which would probably be better off in a new thread. I just tested locally and `{{ craft.snaptcha.fieldValue }}` outputs a value as expected, running Snaptcha version 2.2.0 (you mentioned 2.2.1 which does not yet exist).

**Comment by carolinecblaker** [comment]
Turns out this is 100% me being n00b at what I'm trying to do! There is no bug after all. Thank you for your time and attention.

**Comment by bencroker** [comment]
Sure thing!
