### ISSUE TITLE
Unsure of correct URI pattern for ^catchall urls?

### ISSUE THREAD

**Issue by j-greig** [putyourlightson/craft-snaptcha#6]
I'm trying to exclude all paths that start with "shop" using "^shop" but it doesn't appear to be working... 

(The forms only submit if I exclude the full path, eg "shop/customer/register")

Am I doing something wrong?

Thanks!

PS. This is with Craft CMS 3.3.15

**Comment by j-greig** [comment]
Solution is to use `^/shop` instead of `^shop` (I think)

**Comment by bencroker** [comment]
Yup, that or `^/shop.*` should work!
