### ISSUE TITLE
Project config support?

### ISSUE THREAD

**Issue by heymarkreeves** [putyourlightson/craft-snaptcha#9]
### Is your feature request related to a problem? Please describe.
Does the plugin support project config? I just installed and configured it in dev, pushed out the changes, and there were no `project.yaml`. It's not activated on the live site where admin is disabled.

### Describe the solution you would like
Project config support.

**Comment by bencroker** [comment]
Yes, it should work fine with project config. If `project.yaml` was not modified when you installed the plugin locally then perhaps something is amiss in your local setup? Does installing other plugins modify `project.yaml`?

**Comment by heymarkreeves** [comment]
Gah, I'm sorry. This project had an underlying database conflict I'd narrowed down with Brad and I hadn't cleaned that up yet. I had project config disabled. Sorry, Ben!

**Comment by bencroker** [comment]
Ok, glad to hear you figured it out!
